# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1270, 956)
        MainWindow.setMinimumSize(QtCore.QSize(1136, 862))
        MainWindow.setBaseSize(QtCore.QSize(1169, 896))
        MainWindow.setIconSize(QtCore.QSize(26, 29))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.prev = QtWidgets.QPushButton(self.centralwidget)
        self.prev.setGeometry(QtCore.QRect(800, 770, 75, 23))
        self.prev.setObjectName("prev")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(890, 770, 75, 23))
        self.next.setObjectName("next")
        self.down = QtWidgets.QPushButton(self.centralwidget)
        self.down.setGeometry(QtCore.QRect(730, 850, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.down.setFont(font)
        self.down.setObjectName("down")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(150, 10, 591, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.title.setFont(font)
        self.title.setText("")
        self.title.setObjectName("title")
        self.change = QtWidgets.QPushButton(self.centralwidget)
        self.change.setGeometry(QtCore.QRect(1000, 760, 91, 41))
        self.change.setObjectName("change")
        self.showimg = QtWidgets.QPushButton(self.centralwidget)
        self.showimg.setGeometry(QtCore.QRect(470, 770, 121, 91))
        self.showimg.setObjectName("showimg")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(820, 850, 91, 41))
        self.save.setObjectName("save")
        self.imageview = QtWidgets.QGraphicsView(self.centralwidget)
        self.imageview.setGeometry(QtCore.QRect(20, 110, 960, 640))
        self.imageview.setBaseSize(QtCore.QSize(960, 640))
        self.imageview.setObjectName("imageview")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(20, 110, 960, 640))
        self.label.setBaseSize(QtCore.QSize(960, 640))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.log = QtWidgets.QTextBrowser(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(750, 60, 256, 31))
        self.log.setObjectName("log")
        self.total = QtWidgets.QLabel(self.centralwidget)
        self.total.setGeometry(QtCore.QRect(990, 120, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.total.setFont(font)
        self.total.setObjectName("total")
        self.now = QtWidgets.QLabel(self.centralwidget)
        self.now.setGeometry(QtCore.QRect(680, 770, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.now.setFont(font)
        self.now.setObjectName("now")
        self.prev.raise_()
        self.next.raise_()
        self.down.raise_()
        self.change.raise_()
        self.showimg.raise_()
        self.save.raise_()
        self.imageview.raise_()
        self.label.raise_()
        self.title.raise_()
        self.log.raise_()
        self.total.raise_()
        self.now.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1270, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.prev.setText(_translate("MainWindow", "上一张"))
        self.next.setText(_translate("MainWindow", "下一张"))
        self.down.setText(_translate("MainWindow", "开始"))
        self.change.setText(_translate("MainWindow", "换一套"))
        self.showimg.setText(_translate("MainWindow", "预览"))
        self.save.setText(_translate("MainWindow", "保存"))
        self.total.setText(_translate("MainWindow", "总页面"))
        self.now.setText(_translate("MainWindow", "正在"))
        self.menu.setTitle(_translate("MainWindow", "设计师"))

